// scripts/generateStadiumCoords.ts
/**
 * Generate src/data/stadiumCoords.generated.ts from Wikidata (P625 coordinates).
 *
 * Run:
 *   npx tsx scripts/generateStadiumCoords.ts
 *
 * Notes:
 * - Uses a simple "label equals" lookup. Some stadiums may not match exact labels.
 * - Add more clubs progressively (or swap INPUT to a real list).
 * - Writes a stable TS module consumed by the app at runtime.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { normalizeClubKey } from "../src/data/clubKey";

type StadiumRow = {
  club: string;
  stadium: string;
};

export type StadiumCoordEntry = {
  clubName: string;
  stadiumName: string;
  lat: number;
  lng: number;
  source: "wikidata";
};

const INPUT: StadiumRow[] = [
  { club: "Arsenal", stadium: "Emirates Stadium" },
  { club: "Chelsea", stadium: "Stamford Bridge" },
  { club: "Manchester United", stadium: "Old Trafford" },
];

const OUTPUT_FILE = path.resolve(process.cwd(), "src", "data", "stadiumCoords.generated.ts");

function assertFetch() {
  if (typeof fetch !== "function") {
    throw new Error(
      "Global fetch() is not available. Use Node 18+ (recommended) or polyfill fetch for this script."
    );
  }
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

function parseWktPoint(wkt: string): { lat: number; lng: number } | null {
  // Wikidata returns WKT like: "Point(-0.108611 51.555)"
  const m = String(wkt ?? "").match(/Point\(\s*([-0-9.]+)\s+([-0-9.]+)\s*\)/i);
  if (!m) return null;

  const lng = Number(m[1]);
  const lat = Number(m[2]);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;

  return { lat, lng };
}

async function fetchCoordsByStadiumLabel(stadiumLabel: string): Promise<{ lat: number; lng: number } | null> {
  const label = String(stadiumLabel ?? "").trim();
  if (!label) return null;

  const sparql = `
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX wdt:  <http://www.wikidata.org/prop/direct/>
    SELECT ?coord WHERE {
      ?item rdfs:label "${label.replace(/"/g, '\\"')}"@en.
      ?item wdt:P625 ?coord.
    }
    LIMIT 1
  `.trim();

  const url = "https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(sparql);

  const res = await fetch(url, {
    method: "GET",
    headers: {
      // Wikidata requests a descriptive UA for automated queries
      "User-Agent": "yournextaway/1.0 (stadiumCoords generator; contact: you@example.com)",
      Accept: "application/sparql-results+json",
    },
  });

  if (!res.ok) return null;

  const json: any = await res.json();
  const wkt = json?.results?.bindings?.[0]?.coord?.value;
  if (!wkt) return null;

  return parseWktPoint(String(wkt));
}

function buildGeneratedModule(map: Record<string, StadiumCoordEntry>) {
  // Sort keys for stable diffs
  const sortedKeys = Object.keys(map).sort((a, b) => a.localeCompare(b));
  const sorted: Record<string, StadiumCoordEntry> = {};
  for (const k of sortedKeys) sorted[k] = map[k];

  return `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: scripts/generateStadiumCoords.ts

export type StadiumCoordEntry = {
  clubName: string;
  stadiumName: string;
  lat: number;
  lng: number;
  source: "wikidata";
};

export const STADIUM_COORDS: Record<string, StadiumCoordEntry> = ${JSON.stringify(sorted, null, 2)} as const;
`;
}

async function main() {
  assertFetch();

  console.log("Generating stadiumCoords.generated.ts from Wikidata…");

  const out: Record<string, StadiumCoordEntry> = {};

  for (const row of INPUT) {
    const clubName = String(row.club ?? "").trim();
    const stadiumName = String(row.stadium ?? "").trim();
    const key = normalizeClubKey(clubName);

    if (!clubName || !stadiumName) {
      console.log("✗ Skipping blank row");
      continue;
    }
    if (!key) {
      console.log("✗", clubName, "(could not normalize club key)");
      continue;
    }

    try {
      // Be polite to Wikidata: tiny delay between queries
      await sleep(150);

      const coords = await fetchCoordsByStadiumLabel(stadiumName);
      if (!coords) {
        console.log("✗", clubName, "— no coords found for:", stadiumName);
        continue;
      }

      out[key] = {
        clubName,
        stadiumName,
        lat: coords.lat,
        lng: coords.lng,
        source: "wikidata",
      };

      console.log("✓", clubName, "=>", key);
    } catch (e) {
      console.log("ERR", clubName, "-", (e as any)?.message ?? String(e));
    }
  }

  const content = buildGeneratedModule(out);

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content, "utf8");

  console.log("Wrote:", OUTPUT_FILE);
  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
