// scripts/generateStadiumCoords.ts
/**
 * Generates src/data/stadiumCoords.generated.ts
 *
 * Source: Wikidata SPARQL endpoint (public, free).
 *
 * It queries for football clubs and their home venue coordinates, then outputs
 * a map keyed by normalizeClubKey(clubNameLike).
 *
 * Usage:
 *   npx ts-node scripts/generateStadiumCoords.ts
 *
 * Notes:
 * - You may need: npm i -D ts-node typescript
 * - This is a dev-only generation script. Do not run in app runtime.
 */

import fs from "fs";
import path from "path";

type WikidataBinding = {
  clubLabel?: { value: string };
  stadiumLabel?: { value: string };
  coord?: { value: string }; // "Point(LONG LAT)"
};

type SparqlResponse = {
  results?: { bindings?: WikidataBinding[] };
};

function parsePointWkt(wkt: string): { lat: number; lng: number } | null {
  // "Point(2.3601 48.8414)"
  const m = String(wkt ?? "").match(/Point\(\s*([-\d.]+)\s+([-\d.]+)\s*\)/i);
  if (!m) return null;
  const lng = Number(m[1]);
  const lat = Number(m[2]);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  return { lat, lng };
}

/**
 * Minimal normalizer (mirrors your app normalization style).
 * If your normalizeClubKey differs, you can import it here and use that.
 */
function normalizeClubKey(name: string) {
  return String(name ?? "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/fc\b/g, "")
    .replace(/\bfootball club\b/g, "")
    .replace(/[^\p{L}\p{N}\s-]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * We restrict by country + league membership broadly, but Wikidata is messy.
 * Instead, we pull a wide set and rely on your app keys to match clubs that exist.
 *
 * If you want a stricter query per league, we can do that too.
 */
const SPARQL = `
SELECT ?clubLabel ?stadiumLabel ?coord WHERE {
  ?club wdt:P31/wdt:P279* wd:Q476028.   # instance of association football club
  OPTIONAL { ?club wdt:P115 ?stadium. } # home venue
  OPTIONAL { ?stadium wdt:P625 ?coord. } # coordinate location
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
LIMIT 5000
`;

async function fetchSparql(): Promise<SparqlResponse> {
  const endpoint = "https://query.wikidata.org/sparql";
  const url = `${endpoint}?format=json&query=${encodeURIComponent(SPARQL)}`;

  const res = await fetch(url, {
    headers: {
      "user-agent": "YourNextAway/1.0 (dev script; contact: you@example.com)",
      accept: "application/sparql-results+json",
    },
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Wikidata SPARQL HTTP ${res.status}: ${text}`);
  }

  return (await res.json()) as SparqlResponse;
}

function buildGeneratedFile(entries: Record<string, any>) {
  const header = `// src/data/stadiumCoords.generated.ts
// AUTO-GENERATED by scripts/generateStadiumCoords.ts
// DO NOT EDIT BY HAND.

export type StadiumCoordEntry = {
  clubName?: string;
  stadiumName?: string;
  lat: number;
  lng: number;
};

export const STADIUM_COORDS: Record<string, StadiumCoordEntry> = ${JSON.stringify(entries, null, 2)} as const;
`;

  return header;
}

async function main() {
  console.log("Fetching Wikidata…");
  const json = await fetchSparql();
  const bindings = json?.results?.bindings ?? [];

  const out: Record<string, any> = {};

  for (const b of bindings) {
    const club = b?.clubLabel?.value?.trim();
    const stadium = b?.stadiumLabel?.value?.trim();
    const coordWkt = b?.coord?.value?.trim();

    if (!club || !coordWkt) continue;

    const coord = parsePointWkt(coordWkt);
    if (!coord) continue;

    const key = normalizeClubKey(club);
    if (!key) continue;

    // Only keep first hit unless we find a "better" one later.
    // (Wikidata sometimes has multiple venues/coords.)
    if (!out[key]) {
      out[key] = {
        clubName: club,
        stadiumName: stadium || undefined,
        lat: coord.lat,
        lng: coord.lng,
      };
    }
  }

  const target = path.join(process.cwd(), "src", "data", "stadiumCoords.generated.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });

  fs.writeFileSync(target, buildGeneratedFile(out), "utf8");
  console.log(`Wrote ${target}`);
  console.log(`Entries: ${Object.keys(out).length}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
